repository:
  name: ahmadnassri.com
  description: Ahmad's website
  topics: ahmadnassri
  homepage: https://ahmadnassri.com
  private: true
  has_issues: false
  has_wiki: false
  has_downloads: false
  has_projects: false
  default_branch: master
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: true
