# SEO
title: REFACTOR Conf

description: TODO

url: https://refactorconf.com

lang: en

# author: 
#   name: Ahmad Nassri
#   email: email@ahmadnassri.com
#   uri: https://ahmadnassri.com

twitter:
  username: RefactorConf
  card: summary

facebook:
  admins: 227304446

# logo: /assets/images/logo.png

# social:
#   name: Ahmad Nassri
#   links:
#     - https://twitter.com/ahmadnassri
#     - https://www.facebook.com/ahmad.nassri
#     - https://www.linkedin.com/in/ahmadnassri
#     - https://github.com/ahmadnassri
#     - https://keybase.io/ahmadnassri

# todo
# webmaster_verifications:
  # google: 123
  # bing: 123
  # alexa: 1234
  # yandex: 1234
  # baidu: 1234

# build config

future: true

exclude: 
  - Gemfile
  - Gemfile.lock
  - vendor/bundle
  - ssl
  - Dockerfile
  - docker-compose.yml

sass:
  sass_dir: _sass
  style: compressed

feed:
  collections:
    - events

collections_dir: collections

collections:
  events:
    output: true
    permalink: /:path/index.html

defaults:
  # - scope:
  #     path: ""
  #   values:
  #     image:
  #       path: /assets/images/logo.png
  #       height: 1000
  #       width: 1000

  - scope:
      type: events
    values:
      layout: event
      twitter:
        card: summary_large_image

plugins:
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
