# SEO
title: REFACTOR Conf

description: TODO

url: https://refactorconf.com

lang: en

# author: 
#   name: Ahmad Nassri
#   email: email@ahmadnassri.com
#   uri: https://ahmadnassri.com

twitter:
  username: RefactorConf
  card: summary

facebook:
  admins: 227304446

social:
  name: REFACTOR Conference
  links:
    - https://twitter.com/RefactorConf
    - https://www.linkedin.com/company/tech-masters-community
    - https://github.com/TechnologyMasters

logo: /assets/images/logo.png

# build config

timezone: America/Toronto

future: true

exclude: 
  - Gemfile
  - Gemfile.lock
  - vendor/bundle
  - ssl
  - Dockerfile
  - docker-compose.yml

sass:
  sass_dir: _sass
  style: compressed

# feed:
#   collections:
#     - events

collections_dir: collections

collections:
  events:
    output: true
    permalink: /:path.html

defaults:
  - scope:
      path: ""
    values:
      twitter:
        card: summary_large_image

  - scope:
      type: events
    values:
      layout: event

plugins:
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
